src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $header_image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getHeaderImage(): ?string
    {
        return $this->header_image;
    }

    public function setHeaderImage(?string $header_image): static
    {
        $this->header_image = $header_image;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Entity\Job;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class MainController extends AbstractController
{
    #[Route('/', name: 'app_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {

        $jobs = $entityManager->getRepository(Job::class)->findAllActiveJobsOrderedByDate();

        // Pagination
        $pagination = $paginator->paginate(
            $jobs,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('main/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }


    #[Route('/company-info', name: 'app_company_info', methods: ['GET'])]
    public function companyInfo(EntityManagerInterface $entityManager): Response {
        $companyInformation = $entityManager->getRepository(Company::class)->findAll();

        return $this->json($companyInformation);
    }

}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Discover Our Current Positions{% endblock %}

{% block body %}
    
    <header class="header">

        {% include 'components/_navigation.html.twig' %}

        {% include 'components/_header-image.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1 mb-2">Discover Our Open Positions</h1>

            {% if pagination.totalItemCount > 0 %}

                <div class="jobs">

                {% for job in pagination %}

                    <article class="job">

                        <div class="job__content">

                            <h3 class="job__title">{{ job.title }}</h3>
                            <p class="job__description">{{ job.description|slice(0, 120) }}...</p>
                            <a role="button" class="job__link contrast" href="{{ path('app_job_show', {'id': job.id}) }}">Learn more</a>

                            <div class="features">

                                <span class="feature">{{ job.fte }} %</span>

                                {% for feature in job.features %}

                                    <span class="feature">{{ feature.title }}</span>

                                {% endfor %}

                            </div>

                        </div>
                        
                        <div class="job__image">
                            <img src="/image/jobs/{{ job.headerImage }}" alt="{{ job.title }}">
                        </div>

                    </article>

                {% endfor %}

                {# Pagination controls #}
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>

            </div>

            {% else %}

                <div class="jobs">
                    <p>Currently, no open positions are available.</p>
                </div>

            {% endif %}

        </section>

    </main>

{% endblock %}