src/Entity/Application.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Filesystem\Filesystem;

#[ORM\Entity(repositoryClass: ApplicationRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Application
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $curriculum_vitae = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    private ?User $applicant = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    private ?Job $job = null;

    #[ORM\Column(length: 255)]
    private ?string $letter_of_motivation = null;

    #[ORM\ManyToOne(inversedBy: 'application')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ApplicationStatus $applicationStatus = null;

    #[ORM\Column]
    private ?bool $is_archived = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    #[ORM\PreRemove]
    public function removeFiles(): void
    {
        $filesystem = new Filesystem();

        $cvFilePath = __DIR__ . '/../../var/uploads/applications/' . $this->getCurriculumVitae();
        $motivationLetterFilePath = __DIR__ . '/../../var/uploads/applications/' . $this->getLetterOfMotivation();

        if ($filesystem->exists($cvFilePath)) {
            $filesystem->remove($cvFilePath);
        }

        if ($filesystem->exists($motivationLetterFilePath)) {
            $filesystem->remove($motivationLetterFilePath);
        }
    }

    public function getCurriculumVitae(): ?string
    {
        return $this->curriculum_vitae;
    }

    public function setCurriculumVitae(string $curriculum_vitae): static
    {
        $this->curriculum_vitae = $curriculum_vitae;

        return $this;
    }

    public function getApplicant(): ?User
    {
        return $this->applicant;
    }

    public function setApplicant(?User $applicant): static
    {
        $this->applicant = $applicant;

        return $this;
    }

    public function getJob(): ?Job
    {
        return $this->job;
    }

    public function setJob(?Job $job): static
    {
        $this->job = $job;

        return $this;
    }

    public function getLetterOfMotivation(): ?string
    {
        return $this->letter_of_motivation;
    }

    public function setLetterOfMotivation(string $letter_of_motivation): static
    {
        $this->letter_of_motivation = $letter_of_motivation;

        return $this;
    }

    public function __toString(): string {
        return $this->getApplicant()->getFirstname() . " " . $this->getApplicant()->getLastname() . " applied for " . $this->getJob();
    }

    public function getApplicationStatus(): ?ApplicationStatus
    {
        return $this->applicationStatus;
    }

    public function setApplicationStatus(?ApplicationStatus $applicationStatus): static
    {
        $this->applicationStatus = $applicationStatus;

        return $this;
    }

    public function isArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(bool $is_archived): static
    {
        $this->is_archived = $is_archived;

        return $this;
    }
}

src/Form/ApplicationType.php
<?php

namespace App\Form;

use App\Entity\Application;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ApplicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('applicant', ApplicationUserType::class)
            ->add('curriculum_vitae', FileType::class, [
                'label' => 'Curriculum Vitae (PDF file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF file',
                    ])
                ],
            ])
            ->add('letter_of_motivation', FileType::class, [
                'label' => 'Letter of motivation (PDF file)',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF file',
                    ])
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

src/Controller/ApplicationController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Entity\Job;
use App\Entity\User;
use App\Form\ApplicationResponseType;
use App\Form\ApplicationType;
use App\lib\ApplicationFile;
use App\lib\ApplicationStatusEnum;
use App\lib\FileHelper;
use App\Repository\ApplicationStatusRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Random\RandomException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\String\Slugger\SluggerInterface;

class ApplicationController extends AbstractController
{

    public function __construct(
        private readonly UserPasswordHasherInterface $passwordGenerator,
    ) {}

    /**
     * @throws RandomException
     * @throws TransportExceptionInterface
     */
    #[Route('/apply/{id<\d+>}', name: 'app_job_application_apply', methods: ['GET', 'POST'])]
    public function applyForJob(
        Job $job,
        Request $request,
        UserRepository $userRepository,
        EntityManagerInterface $entityManager,
        SluggerInterface $slugger,
        #[Autowire('%kernel.project_dir%/var/uploads/applications')] string $applicationFilesDirectory,
        MailerInterface $mailer,
        ApplicationStatusRepository $applicationStatusRepository,
    ): Response
    {
        // Create the application form
        $form = $this->createForm(ApplicationType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            // Creating a new Application
            $application = new Application();

            // Retrieve data from the form
            $formData = $form->getData();

            // Handle file uploads
            $cvFile = $form->get('curriculum_vitae')->getData();
            $letter_of_motivation = $form->get('letter_of_motivation')->getData();

            $successfulFileUpload = false;

            if ($cvFile) {
                $successfulFileUpload = FileHelper::saveFileOfApplication(
                    application: $application,
                    applicationFileType: ApplicationFile::CV,
                    fileName: $cvFile,
                    slugger: $slugger,
                    applicationFilesDirectory: $applicationFilesDirectory
                );
            }

            if ( ! $successfulFileUpload ) {
                return $this->redirectToRoute('app_index');
            }

            if ($letter_of_motivation) {
                $successfulFileUpload = FileHelper::saveFileOfApplication(
                    application: $application,
                    applicationFileType: ApplicationFile::Motivation,
                    fileName: $letter_of_motivation,
                    slugger: $slugger,
                    applicationFilesDirectory: $applicationFilesDirectory
                );
            }

            if ( ! $successfulFileUpload ) {
                return $this->redirectToRoute('app_index');
            }

            // Set applicant details from form
            $applicantData = $formData->getApplicant();

            // Try to find user in database
            $user = $userRepository->findByEmail($applicantData->getEmail());

            // If new user, create new user and update user data
            if ( ! $user ) {
                $user = new User();
                $user->setFirstName($applicantData->getFirstName());
                $user->setLastName($applicantData->getLastName());
                $user->setEmail($applicantData->getEmail());

                // Generate a temporary password for the applicant
                $temporaryPassword = bin2hex(random_bytes(20));
                $hashedPassword = $this->passwordGenerator->hashPassword($user, $temporaryPassword);
                $user->setPassword($hashedPassword);

                // Assign ROLE_APPLICANT to the user
                $user->setRoles(['ROLE_APPLICANT']);
            }

            // Set application status to pending (communication with applicant)
            $application->setApplicationStatus($applicationStatusRepository->findStatusById(ApplicationStatusEnum::Pending->value));

            // Set application status to unarchived (to be able to archive applications later)
            $application->setIsArchived(false);

            // Set the Job associated with the Application
            $application->setJob($job);
            $application->setApplicant($user);

            // Persist the user and application
            $entityManager->persist($user);
            $entityManager->persist($application);
            $entityManager->flush();

            // Send confirmation email to applicant
            $email = (new TemplatedEmail())
                ->from(new Address('application@example.com', 'Test Company'))
                ->to($applicantData->getEmail())
                ->subject('Your application has been submitted')
                ->htmlTemplate('emails/application.html.twig')
                ->context(['job' => $job, 'application' => $application]);

            $mailer->send($email);

            // Send update email to admins
            $admins = $userRepository->findAdmins();

            foreach ($admins as $admin) {
                $email = (new TemplatedEmail())
                    ->from(new Address('application@example.com', 'Test Company'))
                    ->to($admin->getEmail())
                    ->subject("New Application for " . $job->getTitle())
                    ->htmlTemplate('emails/application-notification.html.twig')
                    ->context(['job' => $job, 'application' => $application]);

                $mailer->send($email);
            }

            return $this->redirectToRoute('app_job_application_thank_you');
        }

        // Render the application form
        return $this->render('application/apply.html.twig', [
            'form' => $form->createView(),
            'job' => $job,
        ]);
    }

    #[Route('/apply/thank-you', name: 'app_job_application_thank_you', methods: ['GET'])]
    public function thankYou(): Response {
        return $this->render('application/thank_you.html.twig');
    }

    #[Route('/show-application-document/{fileName}}', name: 'show_application_document', methods: ['GET'])]
    public function showApplicationDocument(string $fileName): Response
    {
        $filePath = $this->getParameter('kernel.project_dir') . '/var/uploads/applications/' . $fileName;

        if ( ! file_exists($filePath) ) {
            throw new FileNotFoundException('File not found.');
        }

        return new Response(
            file_get_contents($filePath),
            200,
            [
                'Content-Type' => mime_content_type($filePath),
                'Content-Disposition' => 'inline; filename="' . basename($filePath) . '"',
            ]
        );
    }

    #[Route('/applications', name: 'show_applications', methods: ['GET'])]
    public function showApplications(EntityManagerInterface $entityManager): Response {

        $applications = $entityManager->getRepository(Application::class)->getActiveApplications();

        return $this->render('application/index.html.twig', [
            'applications' => $applications,
        ]);
    }

    #[Route('/applications/{id}', name: 'show_single_application', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function showApplication(EntityManagerInterface $entityManager, int $id): Response {

        $application = $entityManager->getRepository(Application::class)->find($id);

        return $this->render('application/show.html.twig', [
            'application' => $application,
        ]);
    }

    /**
     * @throws TransportExceptionInterface
     */
    #[Route('/applications/{id}/response', name: 'response_to_application', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function responseToApplication(
        EntityManagerInterface $entityManager,
        int $id,
        Request $request,
        MailerInterface $mailer,
    ): Response {

        $application = $entityManager->getRepository(Application::class)->find($id);

        $form = $this->createForm(ApplicationResponseType::class, null, [
            'applicant_name' => $application->getApplicant()->getFullName(),
            'application_status' => $application->getApplicationStatus(),
        ]);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $formData = $form->getData();
            $applicationStatus = $formData['application_status'];
            $responseMessage = $formData['response'];

            $email = (new TemplatedEmail())
                ->from(new Address('application@example.com', 'Test Company'))
                ->to($application->getApplicant()->getEmail())
                ->subject('Your application has been submitted')
                ->htmlTemplate('emails/answer.html.twig')
                ->context(['responseMessage' => $responseMessage, 'application' => $application]);

            $mailer->send($email);

            $application->setApplicationStatus($applicationStatus);
            $entityManager->persist($application);
            $entityManager->flush();

            return $this->redirectToRoute('show_applications');
        }

        return $this->render('application/response.html.twig', [
            'application' => $application,

templates/application/_form.html.twig
{{ form_start(form, { 'attr': { 'class': 'form form__application' } }) }}

    {{ form_row(form.applicant.first_name, {'attr': {'class': 'input'}}) }}

    {{ form_row(form.applicant.last_name, {'attr': {'class': 'input'}}) }}

    {{ form_row(form.applicant.email, {'attr': {'class': 'input'}}) }}

    {{ form_row(form.curriculum_vitae, {'attr': {'class': 'input'}}) }}

    {{ form_row(form.letter_of_motivation, {'attr': {'class': 'input'}}) }}

    <button class="contrast">{{ button_label|default('Apply') }}</button>

{{ form_end(form) }}

templates/application/apply.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ApplicationController!{% endblock %}

{% block body %}
    <style></style>

    <header class="header">

        {% include 'components/_navigation.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1 mb-2">Apply for {{ job.title }}</h1>

            {% include 'application/_form.html.twig' %}

        </section>

    </main>

{% endblock %}

templates/application/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ApplicationController!{% endblock %}

{% block body %}
    <style></style>

    <header class="header">

        {% include 'components/_navigation.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1 mb-2">Applications</h1>

            {% if applications|length > 0 %}

                <table>
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Position</th>
                    <th scope="col">Status</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>

                {% for application in applications %}

                    <tr class="applications-list">
                        <th scope="row">{{ application.applicant }}</th>
                        <td>{{ application.job }}</td>

                        {% if application.applicationStatus == 'Pending' %}
                            <td class="font-application-status">{{ application.applicationStatus }}</td>
                        {% elseif application.applicationStatus == 'Invited' %}
                            <td class="font-application-status--invited">{{ application.applicationStatus }}</td>
                        {% elseif application.applicationStatus == 'Approved' %}
                            <td class="font-application-status--approved">{{ application.applicationStatus }}</td>
                        {% elseif application.applicationStatus == 'Rejected' %}
                            <td class="font-application-status--rejected">{{ application.applicationStatus }}</td>
                        {% endif %}
                        <td>
                            <a href="{{ path('show_single_application', {id: application.id}) }}">Manage Application</a>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>

            </table>

            {% else %}

                <p>No applications yet.</p>

            {% endif %}

        </section>

    </main>

{% endblock %}

templates/application/response.html.twig
{% extends 'base.html.twig' %}

{% block title %}Send Message{% endblock %}

{% block body %}

    <header class="header">

        {% include 'components/_navigation.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1 mb-2">Answer for {{ application.applicant }}</h1>

            <div class="form">

                {{ form(form) }}

            </div>

        </section>

    </main>

{% endblock %}

templates/application/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ApplicationController!{% endblock %}

{% block body %}
    <style></style>

    <header class="header">

        {% include 'components/_navigation.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1 mb-2">{{ application.applicant }}</h1>

            <ul>
                {% if application.applicationStatus == 'Pending' %}
                    <li>Status <span class="application-status">{{ application.applicationStatus }}</span></li>
                {% elseif application.applicationStatus == 'Invited' %}
                    <li>Status <span class="application-status application-status--invited">{{ application.applicationStatus }}</span></li>
                {% elseif application.applicationStatus == 'Approved' %}
                    <li>Status <span class="application-status application-status--approved">{{ application.applicationStatus }}</span></li>
                {% else %}
                    <li>Status <span class="application-status">{{ application.applicationStatus }}</span></li>
                {% endif %}

                <li>{{ application.applicant }}</li>
                <li>{{ application.applicant.email }}</li>
            </ul>

            <h3 class="h3 mb-2">Documents</h3>

            <ul class="mb-2">
                <li>
                    <a href="{{ path('show_application_document', {fileName: application.curriculumVitae}) }}" target="_blank">
                        <strong>Curriculum Vitae</strong>
                    </a>
                </li>
                <li>
                    <a href="{{ path('show_application_document', {fileName: application.letterOfMotivation}) }}" target="_blank">
                        <strong>Letter of Motivation</strong>
                    </a>
                </li>
            </ul>

            <div class="application-actions">
                <a href="{{ path('response_to_application', {id: application.id}) }}" role="button" class="contrast">
                    Write Message
                </a>
            </div>

        </section>

    </main>

{% endblock %}

templates/application/thank_you.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ApplicationController!{% endblock %}

{% block body %}
    <style></style>

    <header class="header">

        {% include 'components/_navigation.html.twig' %}

    </header>

    <main class="main">

        <section class="section">

            <h1 class="h1">Thank you for your application</h1>

            <p>We'll get back to you as quick as possible.</p>

            <a href="{{ path('app_index') }}">
                Back
            </a>

        </section>

    </main>

{% endblock %}